// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdplqNdmhhZOkL485EhKc_ao7UWfYQic',
    appId: '1:802033502936:web:1d74f67e99d45f83bb65ad',
    messagingSenderId: '802033502936',
    projectId: 'mynotes-flutter-app-project',
    authDomain: 'mynotes-flutter-app-project.firebaseapp.com',
    storageBucket: 'mynotes-flutter-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bcdGbIGGZw0SwRV3lCSGwP2Kdlk0MbA',
    appId: '1:802033502936:android:577061d3eb5338e5bb65ad',
    messagingSenderId: '802033502936',
    projectId: 'mynotes-flutter-app-project',
    storageBucket: 'mynotes-flutter-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cx-1p1kntN6BWsdM833YaugPa76vUII',
    appId: '1:802033502936:ios:f764d9ac5b9f3995bb65ad',
    messagingSenderId: '802033502936',
    projectId: 'mynotes-flutter-app-project',
    storageBucket: 'mynotes-flutter-app-project.appspot.com',
    iosClientId: '802033502936-m2ats55fr843burt4ui17r79j8fqu2jm.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
